# Week 03: NumPy and SciPy

This week's learning goals are as follows:

1. Understand and use NumPy broadcasting and matrix/array abstractions.
1. Use advanced NumPy functions to create and modify matrices.
1. ```np.random()```
1. Plot basic scatter plots using Matplotlib.
1. Read and use SciPy documentation (for homework).

This notebook uses the Kaggle Dataset [Pokemon with stats](https://www.kaggle.com/abcsds/pokemon/data). Download and move the csv into ```03_numpy/csvs```.

Uses [Stanford CS231N NumPy tutorial examples.](http://cs231n.github.io/python-numpy-tutorial/#numpy) and [UCSB CHE210D NumPy tutorial](https://engineering.ucsb.edu/~shell/che210d/numpy.pdf).

In [ ]:
# the following code guarantees you'll properly reload any modules that you custom-defined in your environment.
# you don't need to understand it.
# just run this once at the beginning.
# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2
import os
import sys
import numpy as np
import csv

## 1. Basic NumPy

Numpy is a library for science, math and engineering. Its main abstraction is the numpy array, which is a beefed up version of the Python list.

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print('a:\t', a)
print('type:\t', type(a))            # Prints "<class 'numpy.ndarray'>"
print('shape:\t', a.shape)            # Prints "(3,)"
print('elements:\t',a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print('new a:\t', a)                  # Prints "[5, 2, 3]"

 With the numpy array, we can perform simple math operations without worrying about list comprehension.

In [ ]:
x = np.array([2,3,4,5,6,6])
y = np.array([9,32,0,102,-1,-123.0])
# simple operations automatically broadcast to serve every element
print('x\t=', x)
print('2*x\t=', 2*x)
print('x+3\t=', x + 3)
print('x/4\t=', x/4)

In [ ]:
# you can do element-wise addition too
x = np.array([2,3,4,5,6,6])
y = np.array([9,32,0,102,-1,-123.0])
print('x-y\t=', x-y)
print('x*y\t=', x*y)
print('x/y\t=', x/y) # division by zero, note the infinity

### Indexing and slicing

Numpy arrays can be indexed and sliced the same way as Python lists.

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('a:\t', a.shape, '\n', a)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2
b = a[:2, 1:3]
print('b:\t', b.shape, '\n', b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print('top, second from left:', a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print('top, second from left:', a[0, 1])   # Prints "77"
print('a:\n', a)
print('b:\n', b)

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('a:\n', a)

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print('row rank 1', row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print('row rank 2', row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print('col rank 1', col_r1, col_r1.shape) 
print('col rank 2', col_r2, col_r2.shape) 

In fact the slicing is even more flexible in some cases. For example, you can specify individual elements and return them all at once.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,)
print('list indexing\t\t', a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print('per-elt indexing\t', np.array([a[0, 0], a[1, 1], a[2, 0]]))

# When using integer array indexing, you can reuse the same
# element from the source array:
print('repeated indexing\t', a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print('per-elt indexing\t', np.array([a[0, 1], a[0, 1]]))

#### Programming Exercises

After you run the following cell, there will be an array ```a```.
1. Print the shape of ```a```.
1. Print the first row of ```a```.
1. Print the second column of ```a```.
1. Find the array slicing that gives you:

     ```[[ 4  5]
     [10 11]
     [16 17]]```
1. Find the array slicing that gives you:

    ```[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]```

In [ ]:
a = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18]])
print(a)

In [ ]:
# exercise 1

In [ ]:
# exercise 2

In [ ]:
# exercise 3

In [ ]:
# exercise 4
print('target:\n', np.array([[ 4, 5], [10, 11], [16, 17]]))
# your solution below this line

In [ ]:
# exercise 5
print('target:\n', np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]]))

### Element-wise functions

There are some built-in element-wise functions that we will use a lot.

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(np.sqrt(x)) # sqrt(x), element-wise

In [ ]:
print(np.power(x, 3)) # x ^ 3, element-wise

In [ ]:
print(np.log(x)) # ln(x), element-wise

### Array-wise functions

NumPy has all of the basic statistics functions built in, too. These all can perform statistics on each dimension of the input, but by default perform statistics on every element.

In [ ]:
a = np.array([[0, 2], [3, -1], [3, 5]])
print(a)
print(a.mean())

In [ ]:
print(a.mean(axis=0))
print(a.mean(axis=1))

In [ ]:
print(a.std())
print(a.var(axis=0))

In [ ]:
print(np.unique(a))

### Creating new arrays from old ones

Once you create a numpy array, its shape doesn't change. However, you can use it to create new matrices with various numpy functions, or even convert back to lists.

The following code **converts numpy arrays to lists and vice versa.**

In [ ]:
# converting in-between list and numpy array
python_list = [2,3,4,5]
arr = np.array(python_list)
print('list', python_list)
print('np array', arr)
print('back to list', arr.tolist())

**Note on documentation:**

If you are looking at the NumPy documentation, you might see two different versions of the same function:
* Reshape as an object method: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html
    * If you have an array ```a```, you call this via ```a.reshape(...)```
* Reshape as a general numpy method: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape
    * If you have an array ```a```, you call this via ```np.reshape(a, ...)```
    
Is there any difference between these two? No, not really, but sometimes functions are written only in a certain way, and it's good to know that there exist these two options so that you can navigate the NumPy documentation correctly.

In [ ]:
a = np.array(range(10), float)
print('a', a)
b = a.reshape((5, 2)) # call it on a
print('b', b)
c = np.reshape(a, (5, 2)) # general numpy
print('c', c)

Anyway, back to useful array manipulations. ```flatten``` shrinks everything down to one dimension.

In [ ]:
## flatten array into single dimension
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print('original', a, a.shape)
a_flat = a.flatten()
print('flattened', a_flat, a_flat.shape)

You can also concatenate arrays together. Concatenate has an optional argument ```axis``` which specifies what dimension to concatenate on. There are a few options for our callback:
* ```concatenate(list_of_lists) ``` No additional arguments. Default is axis = 0.
* ```concatenate(list_of_lists, axis=1)``` One additional argument. Will attempt to concatenate on axis = 1, i.e., the second axis. This might not always exist, so it might throw an error.

In [ ]:
# concatenating on a single dimension
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
print(np.concatenate((a, b, c)))

In [ ]:
# concatenating on different dimensions
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
print('default along dim 1', np.concatenate((a,b)))
print('explicitly along dim 1', np.concatenate((a,b), axis=0))
print('explicitly along dim 2', np.concatenate((a,b), axis=1))

### Making standard matrices
Because NumPy is a math library, it also has many functions for creating matrices. Let's start with some rooted in linear algebra. The most useful of these is ```np.zeros(shape_of_arr)``` and ```np.ones(shape_of_arr)```.

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print('a\t', a.shape, '\n', a)              

b = np.ones((1,2))    # Create an array of all ones
print('b\t', b.shape, '\n', b)                

c = np.full((2,2), 7)  # Create a constant array
print('c\t', c.shape, '\n', c)                   

d = np.eye(2)         # Create a 2x2 identity matrix
print('d\t', d.shape, '\n', d)                  

Note that the ```x.shape``` function really helps with making matrices. For example, to create a ones matrix with the same shape as a:

In [ ]:
a = np.array([[2,3,4,5,5,6], [2,3,4,5,5,6], [2,3,4,5,5,6]])
print('a\t:', a.shape,'\n', a)
print('zeros:\n', np.zeros(a.shape))

Other useful ones are ```np.arange``` (analogous to Python's range()) and ```np.linspace```.
* ```np.arange(max_item)``` returns an array from 0 to max_item -1, inclusive. Shape is (max_item,).
* ```np.arange(min_item, max_item)``` returns an array from min_item to max_item-1, inclusive.
* ```np.arange(min_item, max_item, step)``` returns an array from min_item to max_item-1, stepping by ```step``` amount.
* ```np.linspace(start, stop)``` returns num evenly spaced samples, calculated over the interval [start, stop], inclusive of stop. Default is ```num = 50```.
* ```np.linspace(start, stop, 23)``` returns 23 evenly spaced samples over the interval.



In [ ]:
print(np.arange(5))
print(np.arange(1, 6, 2))
print(np.arange(1,7,2)) # note that this returns the same thing

In [ ]:
print(np.linspace(0,10,3))
print(np.linspace(0, 50))

#### Programming exercises

1. Return an array whose elements go from -10 to 10 (inclusive) separated by 0.5 using ```np.arange()```.
1. Return an array whose elements go from -10 to 10 (inclusive) separated by 0.5 using ```np.linspace()```. Note that this would not be the best use case of ```np.linspace()```, which requires you to know the number of elements.
1. Return an array whose elements go from 20 to 50 (inclusive) with 30 elements using ```np.linspace()```. Note that this would not be the best use case of ```np.arange()```, which requires you to know the step size.

In [ ]:
# exercise 1

# exercise 2

# exercise 3

Read the documentation for ```np.expand_dims()```: https://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html.

Note that in the below cell, it is impossible to use ```np.concatenate()``` to create a matrix where a, b, c are rows of a 2-d matrix. This is because a, b, c are one-dimensional, and concatenate's ```axis``` argument only works on existing axes of its arguments.
1. Add an additional dimension to each of a, b, c using ```np.expand_dims()```.
1. Now call concatenate on these new arrays to create the target matrix.
1. Finally, convert your new 2-D matrix into a list of lists (hint: call ```arr.tolist()```).

In [ ]:
a, b, c = np.linspace(1, 6, 6), np.linspace(7, 12, 6), np.linspace(13, 18, 6)
target = np.array([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], [7.0, 8.0, 9.0, 10.0, 11.0, 12.0], [13.0, 14.0, 15.0, 16.0, 17.0, 18.0]])
print('target:\t', target.shape, '\n', target)

# exercise 1

# exercise 2

# exercise 3

## 2. Advanced NumPy

### More indexing

Let's do more list indexing.

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)  
b = np.array([0, 2, 0, 1]) # can also just be a list [0, 2, 0, 1], doesn't have to be an array

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

The best part about indexing in Numpy is that you can index elements and mutate just those elements.

In [ ]:
a[np.arange(4), b] += 10
print(a) 

But wait, there's more! You can even index using **boolean arrays**. You will frequently use this to select the elements of an array that satisfy some condition.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # same shape as a
print("a", a)
print("bool", bool_idx) 

In [ ]:
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2]) 

In [ ]:
a[a > 2] += 10 # combine boolean indexing with array mutation
print(a)

#### Programming exercises

1. Use ```np.abs()``` to give you the absolute value (element-wise) of the array a.
1. Use boolean indexing to give you the absolute value (element-wise) of the array a.
    1. Construct a boolean array that will tell you whether each element is less than 0.
    1. Index all of those element using boolean indexing and update them by multiplying by -1.
    
You should be able to complete the second exercise in a single line.

In [ ]:
a = np.array([[-3, 3, -2, 2, -1, 0],[0, -3, 4, 5, -2, -5]])
print(a)
# exercise 1, a single line with print


# exercise 2, a single line with print



### Array math, aka Linear Algebra continued

Because NumPy works with matrices, it implements a lot of concepts from linear algebra.

In [ ]:
# Element-wise multiplication
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Inner product of vectors
v = np.array([9,10])
w = np.array([11, 12])
print(v.dot(w))
print(np.dot(v, w))

In [ ]:
# Matrix / vector product
x = np.array([[1,2],[3,4]])
print(x.dot(v))
print(np.dot(x, v))

In [ ]:
# Matrix / matrix product
y = np.array([[5,6],[7,8]])
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
#### Tranposes
print('x:\n', x)
print('transpose(x):\n',x.T)

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
## Approach 1, not making use of broadcasting
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [ ]:
## Approach 2, hard to read
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print('vv', vv)                 
y = x + vv  # Add x and vv elementwise
print(y)  

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
1. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
1. The arrays can be broadcast together if they are compatible in all dimensions.
1. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
1. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Some examples of broadcasting (again, taken from the CS231N stanford website)

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

In [ ]:
# Add a vector to each column of a matrix
print('x', x)
print('w', w)
print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3)
print(x * 2)

#### Programming Exercises

1. In the below cell, add x and y together to produce target. You may need to transpose; remember that only the last dimension can be broadcast.
1. Implement linear combination using broadcasting and ```np.sum(arr, axis=dim)```:

    ```
    [[3 0]    [-1    [-3
     [1 2]] *  1 ] =  1]
     ```

In [ ]:
# Exercise 1
x = np.array([[3,4,5],[5,4,3]])
y = np.array([-1,1])
target = np.array([[2, 3, 4], [6, 5, 4]])
print('target:\n',target)


In [ ]:
H = np.array([[3,0], [1,2]])
x = np.array([-1,1])
target = H.dot(x)
print('target:\n', target)

## 3. np.random()

Finally, random numbers!!!! NumPy has a whole bunch of implementations of probability distributions that might be useful to you.

* ```np.random.random(shape)``` Creates an array filled with random values uniformly selected between [0, 1).
* ```np.random.randint(stop, size=None)``` or ```np.random.randint(start, stop, size=None)```. Returns a random integer up to stop (exclusive) or from start to stop-1 (inclusive). If size=None, return a single integer. If size=(3,1), return an array (3,1) of random integers.
* ```np.random.choice(arr, size=None)``` Returns a random selection from the array ```arr```. If size=(3,1), return an array of shape (3, 1) of random choices from ```arr```, with replacement.
* ```np.random.shuffle(arr)``` Shuffles an array in-place. Note that this doesn't return anything; it modifies the original array.

In [ ]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

In [ ]:
np.random.randint(5, 10 ,size=(3,1))

In [ ]:
np.random.choice([2,34,1,-2,30,4])

In [ ]:
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

You can also look for common distributions, like Poisson or Normal.

In [ ]:
print(np.random.poisson(6.0))
print(np.random.normal(1.5, 4.0)) # mean, stdev
print(np.random.normal()) # zero mean, unit var

#### Programming exercises
1. Write a program that generates a Bernoulli random variable which returns 1 with probability p and 0 with probability 1 - p. Hint: use ```np.random.random()```, which returns a single float uniformly between 0 and 1.

1. Write a problem that generates a Bernoulli RV array of size ```size```. Hint: use np.random.random() to generate an array that is the right size, and then use boolean indexing.

In [ ]:
# exercise 1
def bernoulli(p):
    # with probability p (0 <= p <= 1), return 1
    # otherwise, with probability 1 - p, return 0
    pass

In [ ]:
# exercise 2
def bernoulli_arr(p, size):
    pass

## 4. Basics of Matplotlib

In this section we'll talk about how to use NumPy combined with our file-reading techniques from last time to find statistics about data. Then, we'll also learn some basic graphing to visualize data. This will be useful for your homework, and we will continue discussing Matplotlib next week.

Matplotlib is a graphing software for Python that heavily relies on the Numpy array abstraction.

In [ ]:
import matplotlib.pyplot as plt

Plotting is pretty straight forward:
1. Prepare your data
1. For every line/data series, call the corresponding plotting function. This week we are only using the ```plt.plot(..)``` and ```plt.scatter(...)``` functions. You can call this as many times as you want; Matplotlib will keep plotting onto the same figure.
1. Add your labels.
1. ```plt.show()``` displays the figure.

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine']) # note the labels are in the order we plotted
plt.show()

If you don't want line plots and instead you want scatter plots, that's easy too. I've also passed in a parameter ```c``` that can specify our colors, and a ```label``` parameter that labels the series directly.

The full color list with names is here: https://matplotlib.org/2.0.0/examples/color/named_colors.html

In [ ]:
# scatter plot version
plt.scatter(x, y_sin, c='k', label='Sine')
plt.scatter(x, y_cos, c='b', label='Cosine')
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend() # note the empty call, since our series are now named
plt.show()

You can also save these plots. You do this as follows:

1. ```fig = plt.figure()```
1. Do your stuff
1. ```fig.savefig('out.png')```

In [ ]:
fig = plt.figure()
plt.scatter(x, y_sin, c='k')
plt.scatter(x, y_cos, c='b')
plt.show()
fig.savefig('out.png')
# Figure saved to os.getcwd()
print(os.getcwd())

## 5. Homework

* ```problem_01.ipynb``` Graphing with NumPy and Matplotlib
* ```problem_02.ipynb``` Using SciPy